package security

import "strings"

// commonPasswords contains a curated list of the most commonly used passwords
// Based on data from breach databases and security research
// Sources: Have I Been Pwned, SecLists, and password breach compilations
var commonPasswords = map[string]bool{
	"123456":         true,
	"password":       true,
	"12345678":       true,
	"qwerty":         true,
	"123456789":      true,
	"12345":          true,
	"1234":           true,
	"111111":         true,
	"1234567":        true,
	"dragon":         true,
	"123123":         true,
	"baseball":       true,
	"iloveyou":       true,
	"trustno1":       true,
	"1234567890":     true,
	"superman":       true,
	"qwertyuiop":     true,
	"1qaz2wsx":       true,
	"monkey":         true,
	"letmein":        true,
	"password1":      true,
	"password123":    true,
	"abc123":         true,
	"qwerty123":      true,
	"admin":          true,
	"welcome":        true,
	"welcome1":       true,
	"welcome123":     true,
	"passw0rd":       true,
	"password!":      true,
	"p@ssw0rd":       true,
	"p@ssword":       true,
	"football":       true,
	"soccer":         true,
	"master":         true,
	"michael":        true,
	"jennifer":       true,
	"jordan":         true,
	"michelle":       true,
	"daniel":         true,
	"jessica":        true,
	"ashley":         true,
	"princess":       true,
	"sunshine":       true,
	"shadow":         true,
	"starwars":       true,
	"123qwe":         true,
	"654321":         true,
	"qazwsx":         true,
	"121212":         true,
	"000000":         true,
	"696969":         true,
	"555555":         true,
	"666666":         true,
	"123321":         true,
	"7777777":        true,
	"123abc":         true,
	"passw0rd1":      true,
	"password2":      true,
	"password12":     true,
	"qwerty1":        true,
	"qwerty12":       true,
	"zxcvbnm":        true,
	"asdfgh":         true,
	"asdfghjkl":      true,
	"102030":         true,
	"1q2w3e4r":       true,
	"1q2w3e4r5t":     true,
	"q1w2e3r4":       true,
	"flower":         true,
	"password1234":   true,
	"hello":          true,
	"hello123":       true,
	"starwars1":      true,
	"charlie":        true,
	"aa123456":       true,
	"computer":       true,
	"freedom":        true,
	"whatever":       true,
	"nicholas":       true,
	"summer":         true,
	"winter":         true,
	"champion":       true,
	"thunder":        true,
	"passw0rd123":    true,
	"p@ssw0rd1":      true,
	"p@ssw0rd123":    true,
	"password!1":     true,
	"password@1":     true,
	"admin123":       true,
	"root":           true,
	"toor":           true,
	"test":           true,
	"test123":        true,
	"testing":        true,
	"testing123":     true,
	"guest":          true,
	"changeme":       true,
	"default":        true,
	"temp":           true,
	"temp123":        true,
	"temporary":      true,
	"secret":         true,
	"secret123":      true,
	"123456a":        true,
	"a123456":        true,
	"password123456": true,
	"mypassword":     true,
	"mypass":         true,
	"mypass123":      true,
	"qwer1234":       true,
	"1qazxsw2":       true,
	"zaq12wsx":       true,
	"1q2w3e":         true,
	"123qweasd":      true,
	"google":         true,
	"google123":      true,
	"facebook":       true,
	"facebook123":    true,
	"instagram":      true,
	"linkedin":       true,
	"twitter":        true,
	"amazon":         true,
	"netflix":        true,
	"youtube":        true,
	"pokemon":        true,
	"naruto":         true,
	"batman":         true,
	"spiderman":      true,
	"ironman":        true,
	"superman1":      true,
	"starwars123":    true,
	"matrix":         true,
	"matrix123":      true,
	"123456789a":     true,
	"abcd1234":       true,
	"qwerty12345":    true,
	"password12345":  true,
	"1234qwer":       true,
	"qwer1234asdf":   true,
	"1234567890a":    true,
	"killer":         true,
	"Senha123":       true,
	"senha123":       true,
	"senha":          true,
	"Senha":          true,
	"senha1234":      true,
	"Senha1234":      true,
	"senha@123":      true,
	"Senha@123":      true,
}

// IsCommonPassword checks if a password is in the common passwords list
// Returns true if the password is commonly used (case-insensitive)
func IsCommonPassword(password string) bool {
	// Check exact match
	if commonPasswords[password] {
		return true
	}

	// Check lowercase version
	if commonPasswords[strings.ToLower(password)] {
		return true
	}

	return false
}
